### ISSUE TITLE
0.3.7 is broken

### ISSUE THREAD

**Issue by zloirock** [Automattic/cli-table#152]
After updating implicit `cli-table` dependency from `0.3.6` that works fine to `0.3.7`, I have:

![image](https://user-images.githubusercontent.com/2213682/142248333-a7b16cff-e1c9-4420-84f6-a099aee36d78.png)

How to reproduce it - copy https://github.com/zloirock/core-js/tree/1aaa9b1144b444e9fa1376e2f1d72c34fb99b83e and run `npm run r`.

**Comment by zloirock** [comment]
https://github.com/zloirock/core-js/runs/4240992349?check_suite_focus=true

**Comment by dmeeks91** [comment]
Can confirm that I am seeing the same error.

**Comment by dmeeks91** [comment]
Can confirm that I am seeing the same error.

[This line](https://github.com/Automattic/cli-table/blob/616f9f022c317cc8c5834a8b4be612367a533009/lib/utils.js#L85) will throw an error if typeof `stripped` != "string" Looks like PR #149 introduced a scenario where this scenario is false.

I haven't studied the code enough to determine if the preferred solution is to type check in the [strlen](https://github.com/Automattic/cli-table/blob/616f9f022c317cc8c5834a8b4be612367a533009/lib/utils.js#L83-L87) utility function or revert the newly merged PR.

**Comment by dmeeks91** [comment]
Can confirm that I am seeing the same error.

[This line](https://github.com/Automattic/cli-table/blob/616f9f022c317cc8c5834a8b4be612367a533009/lib/utils.js#L85) will throw an error if `typeof stripped != "string" `
Looks like PR #149 introduced a scenario where this constraint is not met. I'm guessing this is when the bug was introduced.

I haven't studied the code enough to determine if the preferred solution is to type check in the [strlen](https://github.com/Automattic/cli-table/blob/616f9f022c317cc8c5834a8b4be612367a533009/lib/utils.js#L83-L87) utility function or revert the recently merged PR.

**Comment by pomek** [comment]
I face the same issue. In my case, I decided to cast all numbers I pass into the table to strings. It helped.

**Comment by adrianosmond** [comment]
`var stripped = ("" + str).replace(code,'');`
was changed to 
`var stripped = stripAnsi(str);`

so numbers aren't getting converted to strings before stripping them. Maybe 
`var stripped = stripAnsi("" + str);` 
would be a friendlier, more backwards compatible approach?

**Comment by dreinert1994** [comment]
This problem is currently crashing my build pipeline as it is a dependency of a dependency for us. I put a PR to try and resolve the issue, hoping to get it reviewed and merged ASAP

**Comment by ljharb** [comment]
See #160 - any inclusion of `strip-ansi` v6 is a breaking change, because it drops support for node < 12, and the v0.3 line claims support for node 0.2+.
